// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Jomaya.Frontend.Infrastructure.Agents.AutoService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Auto
    {
        /// <summary>
        /// Initializes a new instance of the Auto class.
        /// </summary>
        public Auto() { }

        /// <summary>
        /// Initializes a new instance of the Auto class.
        /// </summary>
        public Auto(string kenteken, string type, long? id = default(long?), long? klantId = default(long?))
        {
            Id = id;
            Kenteken = kenteken;
            Type = type;
            KlantId = klantId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kenteken")]
        public string Kenteken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantId")]
        public long? KlantId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Kenteken == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Kenteken");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (this.Kenteken != null)
            {
                if (this.Kenteken.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Kenteken", 10);
                }
            }
        }
    }
}
