// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Jomaya.Frontend.Infrastructure.Agents.AutoService
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AutoServiceClient.
    /// </summary>
    public static partial class AutoServiceClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<string> ApiAutoGet(this IAutoServiceClient operations)
            {
                return Task.Factory.StartNew(s => ((IAutoServiceClient)s).ApiAutoGetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<string>> ApiAutoGetAsync(this IAutoServiceClient operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiAutoGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='auto'>
            /// </param>
            public static object PostCreateAuto(this IAutoServiceClient operations, Auto auto = default(Auto))
            {
                return Task.Factory.StartNew(s => ((IAutoServiceClient)s).PostCreateAutoAsync(auto), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='auto'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostCreateAutoAsync(this IAutoServiceClient operations, Auto auto = default(Auto), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostCreateAutoWithHttpMessagesAsync(auto, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='onderhoudsopdracht'>
            /// </param>
            public static object PutUpdateOnderhoudsopdracht(this IAutoServiceClient operations, Onderhoudsopdracht onderhoudsopdracht = default(Onderhoudsopdracht))
            {
                return Task.Factory.StartNew(s => ((IAutoServiceClient)s).PutUpdateOnderhoudsopdrachtAsync(onderhoudsopdracht), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='onderhoudsopdracht'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PutUpdateOnderhoudsopdrachtAsync(this IAutoServiceClient operations, Onderhoudsopdracht onderhoudsopdracht = default(Onderhoudsopdracht), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PutUpdateOnderhoudsopdrachtWithHttpMessagesAsync(onderhoudsopdracht, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='onderhoudsopdracht'>
            /// </param>
            public static object PostCreateOnderhoudsopdracht(this IAutoServiceClient operations, Onderhoudsopdracht onderhoudsopdracht = default(Onderhoudsopdracht))
            {
                return Task.Factory.StartNew(s => ((IAutoServiceClient)s).PostCreateOnderhoudsopdrachtAsync(onderhoudsopdracht), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='onderhoudsopdracht'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostCreateOnderhoudsopdrachtAsync(this IAutoServiceClient operations, Onderhoudsopdracht onderhoudsopdracht = default(Onderhoudsopdracht), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostCreateOnderhoudsopdrachtWithHttpMessagesAsync(onderhoudsopdracht, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
