// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Jomaya.Frontend.Infrastructure.Agents.KlantService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Klant
    {
        /// <summary>
        /// Initializes a new instance of the Klant class.
        /// </summary>
        public Klant() { }

        /// <summary>
        /// Initializes a new instance of the Klant class.
        /// </summary>
        public Klant(long? id = default(long?), string voorletters = default(string), string tussenvoegsel = default(string), string achternaam = default(string), string telefoonnummer = default(string))
        {
            Id = id;
            Voorletters = voorletters;
            Tussenvoegsel = tussenvoegsel;
            Achternaam = achternaam;
            Telefoonnummer = telefoonnummer;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "voorletters")]
        public string Voorletters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tussenvoegsel")]
        public string Tussenvoegsel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "achternaam")]
        public string Achternaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "telefoonnummer")]
        public string Telefoonnummer { get; set; }

    }
}
