version: '2'

services:
  mysql-klantservice:
    image: mysql
    container_name: mysql-klantservice
    environment:
      MYSQL_PASSWORD: jomaya
      MYSQL_DATABASE: jomaya-klantservice
      MYSQL_USER: jomaya
      MYSQL_ROOT_PASSWORD: jomaya123
    ports:
      - 4001:3306
    networks: 
      - jomaya-klantenservice
    volumes:
      - c:/TFS/jomaya/db/klantenservice/:/var/lib/mysql
  phpmyadmin-klantservice:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-klantservice
    links:
     - mysql-klantservice:db
    ports:
     - 4002:80
    networks: 
      - jomaya-klantenservice
  Jomaya.klantservice.Facade:
    image: user/jomaya.klantenservice.facade${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      'ConnectionStrings:DataAccessMySqlProvider': server=db;userid=jomaya;password=jomaya;database=jomaya-klantservice;
      'ConnectionStrings:RabbitMQ': rabbitmq
    restart: ON_FAILURE
    links:
     - mysql-klantservice:db
    external_links:
     - rabbitmq:rabbitmq
    ports:
      - 4003:80
    networks: 
     jomaya-eventbus:
       aliases:
         - jomaya-klantenservice
     jomaya-klantenservice:

networks:
  jomaya-eventbus:
    external:
      name: jomaya-eventbus
  jomaya-klantenservice:
    external:
      name: jomaya-klantenservice